version: "3"
services:
  hub:
    image: selenium/hub:3.14
    shm_size: '1gb'
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: kirans/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: kirans/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result:/usr/share/udemy/test-output